### ISSUE TITLE
Cambiar Link a NavLink en las barras de navegación

### ISSUE THREAD

**Issue by adrgarcha** [adrgarcha/mariwano-web#4]
Cambiar los enlaces "Link" que existen actualmente en las barras de navegación (Navbar y Sidebar) por NavLink para mejorar la accesibilidad: https://reactrouter.com/en/main/components/nav-link.

**Comment by davider0** [comment]
[cambios propuestos](https://github.com/adrgarcha/mariwano-web/commit/acc2b4bfd76b5aa7c3cbc8fc2f50d44259864023)
